### ISSUE TITLE
Revisão dos links das redes sociais

### ISSUE THREAD

**Issue by ericbrasiln** [LABHDUFBA/labhdufba.github.io#39]
Precisamos revisar todos os links das redes sociais da equipe.

**Comment by tutzlima** [comment]
## Membros com problemas nos links

- Leonardo Fernandes

  - Linkedin

- Rosana Moore

  - Todas as redes

- Alan Mocellim

  - Linkedin

- Jorge Henrique

  - Sem redes

- Bruno Durães

  - Todas as redes

- Guilherme Kauan

  - Lattes com ícone do linkedin

- Daniel Romero

  - Sem redes

- Alisson Magalhães

  - Posição do ícone está errada
