### ISSUE TITLE
Incluir bolsistas no site do LABHDUFBA

### ISSUE THREAD

**Issue by ericbrasiln** [LABHDUFBA/labhdufba.github.io#59]
Incluir dados dos novos bolsistas da Unilab ao site do LABHDUFBA.

Enviar para @ericbrasiln pelo telegram:

- [x] Jaime: biografia (5 linhas) e uma foto quadrada
- [x] Aparício: biografia (5 linhas) e uma foto quadrada

**Comment by l-thibau** [comment]
Feito ☕
